---
OpenShift Virt Operator 
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-openshift-virt
  namespace: open-cluster-management-global-set
  creationTimestamp: 2024-07-11T16:24:48Z
  generation: 3
  managedFields:
  resourceVersion: "242112"
  uid: c52ffca3-84e1-49cd-9381-c91ac78a291f
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-ovirt
        spec:
          name: ovirt-operator
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: kubevirt-hyperconverged
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: None
status:
  compliant: NonCompliant
  placement:
    - placement: global
      placementBinding: install-openshift-virt-placement
  status:
    - clustername: local-cluster
      clusternamespace: local-cluster
      compliant: NonCompliant
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: global
  namespace: open-cluster-management-global-set
  creationTimestamp: 2024-07-11T16:21:24Z
  generation: 1
  resourceVersion: "235998"
  uid: 9a9d9de4-33d4-4622-977a-c991a8c63b7c
spec:
  clusterSets:
    - global
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Equal
    - key: cluster.open-cluster-management.io/unavailable
      operator: Equal
status:
  conditions:
    - lastTransitionTime: 2024-07-11T16:21:24Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2024-07-11T16:21:24Z
      message: All cluster decisions scheduled
      reason: AllDecisionsScheduled
      status: "True"
      type: PlacementSatisfied
  decisionGroups:
    - clusterCount: 1
      decisionGroupIndex: 0
      decisionGroupName: ""
      decisions:
        - global-decision-1
  numberOfSelectedClusters: 1
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-openshift-virt-placement
  namespace: open-cluster-management-global-set
  creationTimestamp: 2024-07-11T16:24:48Z
  generation: 1
  resourceVersion: "238986"
  uid: 4d6f44dd-eb84-4ea4-8351-fc0fe8e0eefc
placementRef:
  name: global
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: install-openshift-virt
    apiGroup: policy.open-cluster-management.io
    kind: Policy

---
MTV Operator 
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-mtv
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-mtv
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: release-v.2.6
            version: 2.6.2
            installPlanApproval: Automatic
            upgradeApproval: Automatic 
            name: mtv-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace      
---

FAR Operator (Fencing Agent)
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-far
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-far
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: stable
            version: 0.4.0
            installPlanApproval: Automatic
            upgradeApproval: Automatic 
            name: far-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            
---
OADP Operator
---            
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-oadp
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-oadp
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: stable-1.3
            version: 1.3.2
            installPlanApproval: Automatic
            upgradeApproval: Automatic 
            name: oadp-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace              
---
AAP Operator
---            
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-aap
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-aap
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: stable-2.4-cluster-scoped
            installPlanApproval: Automatic
            upgradeApproval: Automatic 
            name: aap-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace        
---
NMstate Operator (Network Manager)
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
---                  
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-nmstate
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-nmstate
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            channel: stable
            installPlanApproval: Automatic
            upgradeApproval: Automatic 
            name: nmstateoperator
            source: redhat-operators
            sourceNamespace: openshift-marketplace                         
